# Generated by Django 4.0.4 on 2023-12-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_api_imitation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RegularSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро'), ('CNY', 'Юань'), ('TRY', 'Турецкая лира'), ('DHS', 'Дирхам ОЭА')], max_length=3, verbose_name='Валюта')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('period', models.CharField(choices=[('DY', 'день'), ('WK', 'неделя'), ('MH', 'месяц'), ('YR', 'год')], max_length=2, verbose_name='Период траты')),
                ('period_count', models.PositiveIntegerField()),
                ('payment_url', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро'), ('CNY', 'Юань'), ('TRY', 'Турецкая лира'), ('DHS', 'Дирхам ОЭА')], max_length=3, verbose_name='Валюта')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('goal_name', models.CharField(max_length=80)),
                ('put_aside_percent', models.PositiveIntegerField(verbose_name='Процент, который готов отложить')),
                ('period_type', models.CharField(max_length=2)),
                ('period_count', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialAssistantBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_confirmed', models.BooleanField(default=False, verbose_name='Доступ подтверждён')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_api_imitation.bankaccount', verbose_name='Банк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CashInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро'), ('CNY', 'Юань'), ('TRY', 'Турецкая лира'), ('DHS', 'Дирхам ОЭА')], max_length=3, verbose_name='Валюта')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
