# Generated by Django 4.0.4 on 2023-12-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('access_key', models.UUIDField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_api_imitation.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('USD', 'Доллар'), ('EUR', 'Евро'), ('CNY', 'Юань'), ('TRY', 'Турецкая лира'), ('DHS', 'Дирхам ОЭА')], max_length=3, verbose_name='Валюта')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
                ('product_type', models.CharField(choices=[('BD', 'Вклады'), ('BC', 'Карты/счета'), ('BA', 'Для бизнеса'), ('IV', 'Инвестиции')], max_length=3, verbose_name='Тип банковского продукта')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_api_imitation.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('operation_date_time', models.DateTimeField()),
                ('type_of_spend', models.CharField(choices=[('SP', 'Покупки в магазинах'), ('TP', 'Проезд в общественном транспорте'), ('TI', 'Связь и интернет'), ('CR', 'Рестораны и кафе'), ('CT', 'Переводы'), ('EN', 'Развлечения'), ('FU', 'Топливо'), ('CB', 'Кэшбэк'), ('SA', 'Зарплата'), ('SC', 'Стипендия'), ('SP', 'Социальные выплаты'), ('OT', 'Другие траты')], max_length=2, verbose_name='Тип операции')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='bank_api_imitation.bankproduct', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='bank_api_imitation.bankproduct', verbose_name='Отправитель')),
            ],
        ),
    ]
