# Generated by Django 4.0.4 on 2023-12-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api_imitation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankproduct',
            name='user',
        ),
    ]
